// app/[[...slug]]/page.js
import Link from 'next/link';

export default function DynamicPage({ params }) {
  // If we are at the homepage, slug will be undefined
  const path = params.slug ? params.slug.join('/') : 'home';
  
  // Create a "random" description for the "autogenerated" feel
  const descriptions = [
    "A mysterious land of code and wonder.",
    "A page that didn't exist until you clicked it.",
    "Part of a vast, infinite digital universe.",
    "A quiet corner of the internet, just for you."
  ];
  const randomDesc = descriptions[path.length % descriptions.length];

  return (
    <div style={{ padding: '50px', fontFamily: 'sans-serif', textAlign: 'center' }}>
      <h1>Welcome to the <u>{path}</u> page</h1>
      <p style={{ fontSize: '1.2rem', color: '#666' }}>{randomDesc}</p>
      
      <div style={{ marginTop: '40px', border: '1px solid #ddd', padding: '20px', borderRadius: '10px' }}>
        <h3>Autogenerate a new page:</h3>
        <p>Click any link below to "create" a page that doesn't exist yet.</p>
        
        <ul style={{ listStyle: 'none', padding: 0, display: 'flex', gap: '15px', justifyContent: 'center' }}>
          <li><Link href="/adventure">/adventure</Link></li>
          <li><Link href="/secret/room">/secret/room</Link></li>
          <li><Link href={`/random-${Math.floor(Math.random() * 1000)}`}>/random-link</Link></li>
          <li><Link href="/">Back Home</Link></li>
        </ul>
      </div>

      <footer style={{ marginTop: '50px', fontSize: '0.8rem' }}>
        Current URL Path: <code>/{params.slug ? params.slug.join('/') : ''}</code>
      </footer>
    </div>
  );
}
